# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/terrainwax/Repo/cpp_indie_studio

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/terrainwax/Repo/cpp_indie_studio

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/terrainwax/Repo/cpp_indie_studio/CMakeFiles /home/terrainwax/Repo/cpp_indie_studio/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/terrainwax/Repo/cpp_indie_studio/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named IrrlichtCMake

# Build rule for target.
IrrlichtCMake: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 IrrlichtCMake
.PHONY : IrrlichtCMake

# fast build rule for target.
IrrlichtCMake/fast:
	$(MAKE) -f CMakeFiles/IrrlichtCMake.dir/build.make CMakeFiles/IrrlichtCMake.dir/build
.PHONY : IrrlichtCMake/fast

Src/ActionManager.o: Src/ActionManager.cpp.o

.PHONY : Src/ActionManager.o

# target to build an object file
Src/ActionManager.cpp.o:
	$(MAKE) -f CMakeFiles/IrrlichtCMake.dir/build.make CMakeFiles/IrrlichtCMake.dir/Src/ActionManager.cpp.o
.PHONY : Src/ActionManager.cpp.o

Src/ActionManager.i: Src/ActionManager.cpp.i

.PHONY : Src/ActionManager.i

# target to preprocess a source file
Src/ActionManager.cpp.i:
	$(MAKE) -f CMakeFiles/IrrlichtCMake.dir/build.make CMakeFiles/IrrlichtCMake.dir/Src/ActionManager.cpp.i
.PHONY : Src/ActionManager.cpp.i

Src/ActionManager.s: Src/ActionManager.cpp.s

.PHONY : Src/ActionManager.s

# target to generate assembly for a file
Src/ActionManager.cpp.s:
	$(MAKE) -f CMakeFiles/IrrlichtCMake.dir/build.make CMakeFiles/IrrlichtCMake.dir/Src/ActionManager.cpp.s
.PHONY : Src/ActionManager.cpp.s

Src/Clock.o: Src/Clock.cpp.o

.PHONY : Src/Clock.o

# target to build an object file
Src/Clock.cpp.o:
	$(MAKE) -f CMakeFiles/IrrlichtCMake.dir/build.make CMakeFiles/IrrlichtCMake.dir/Src/Clock.cpp.o
.PHONY : Src/Clock.cpp.o

Src/Clock.i: Src/Clock.cpp.i

.PHONY : Src/Clock.i

# target to preprocess a source file
Src/Clock.cpp.i:
	$(MAKE) -f CMakeFiles/IrrlichtCMake.dir/build.make CMakeFiles/IrrlichtCMake.dir/Src/Clock.cpp.i
.PHONY : Src/Clock.cpp.i

Src/Clock.s: Src/Clock.cpp.s

.PHONY : Src/Clock.s

# target to generate assembly for a file
Src/Clock.cpp.s:
	$(MAKE) -f CMakeFiles/IrrlichtCMake.dir/build.make CMakeFiles/IrrlichtCMake.dir/Src/Clock.cpp.s
.PHONY : Src/Clock.cpp.s

Src/Cube.o: Src/Cube.cpp.o

.PHONY : Src/Cube.o

# target to build an object file
Src/Cube.cpp.o:
	$(MAKE) -f CMakeFiles/IrrlichtCMake.dir/build.make CMakeFiles/IrrlichtCMake.dir/Src/Cube.cpp.o
.PHONY : Src/Cube.cpp.o

Src/Cube.i: Src/Cube.cpp.i

.PHONY : Src/Cube.i

# target to preprocess a source file
Src/Cube.cpp.i:
	$(MAKE) -f CMakeFiles/IrrlichtCMake.dir/build.make CMakeFiles/IrrlichtCMake.dir/Src/Cube.cpp.i
.PHONY : Src/Cube.cpp.i

Src/Cube.s: Src/Cube.cpp.s

.PHONY : Src/Cube.s

# target to generate assembly for a file
Src/Cube.cpp.s:
	$(MAKE) -f CMakeFiles/IrrlichtCMake.dir/build.make CMakeFiles/IrrlichtCMake.dir/Src/Cube.cpp.s
.PHONY : Src/Cube.cpp.s

Src/GraphicManager.o: Src/GraphicManager.cpp.o

.PHONY : Src/GraphicManager.o

# target to build an object file
Src/GraphicManager.cpp.o:
	$(MAKE) -f CMakeFiles/IrrlichtCMake.dir/build.make CMakeFiles/IrrlichtCMake.dir/Src/GraphicManager.cpp.o
.PHONY : Src/GraphicManager.cpp.o

Src/GraphicManager.i: Src/GraphicManager.cpp.i

.PHONY : Src/GraphicManager.i

# target to preprocess a source file
Src/GraphicManager.cpp.i:
	$(MAKE) -f CMakeFiles/IrrlichtCMake.dir/build.make CMakeFiles/IrrlichtCMake.dir/Src/GraphicManager.cpp.i
.PHONY : Src/GraphicManager.cpp.i

Src/GraphicManager.s: Src/GraphicManager.cpp.s

.PHONY : Src/GraphicManager.s

# target to generate assembly for a file
Src/GraphicManager.cpp.s:
	$(MAKE) -f CMakeFiles/IrrlichtCMake.dir/build.make CMakeFiles/IrrlichtCMake.dir/Src/GraphicManager.cpp.s
.PHONY : Src/GraphicManager.cpp.s

Src/Main.o: Src/Main.cpp.o

.PHONY : Src/Main.o

# target to build an object file
Src/Main.cpp.o:
	$(MAKE) -f CMakeFiles/IrrlichtCMake.dir/build.make CMakeFiles/IrrlichtCMake.dir/Src/Main.cpp.o
.PHONY : Src/Main.cpp.o

Src/Main.i: Src/Main.cpp.i

.PHONY : Src/Main.i

# target to preprocess a source file
Src/Main.cpp.i:
	$(MAKE) -f CMakeFiles/IrrlichtCMake.dir/build.make CMakeFiles/IrrlichtCMake.dir/Src/Main.cpp.i
.PHONY : Src/Main.cpp.i

Src/Main.s: Src/Main.cpp.s

.PHONY : Src/Main.s

# target to generate assembly for a file
Src/Main.cpp.s:
	$(MAKE) -f CMakeFiles/IrrlichtCMake.dir/build.make CMakeFiles/IrrlichtCMake.dir/Src/Main.cpp.s
.PHONY : Src/Main.cpp.s

Src/Map.o: Src/Map.cpp.o

.PHONY : Src/Map.o

# target to build an object file
Src/Map.cpp.o:
	$(MAKE) -f CMakeFiles/IrrlichtCMake.dir/build.make CMakeFiles/IrrlichtCMake.dir/Src/Map.cpp.o
.PHONY : Src/Map.cpp.o

Src/Map.i: Src/Map.cpp.i

.PHONY : Src/Map.i

# target to preprocess a source file
Src/Map.cpp.i:
	$(MAKE) -f CMakeFiles/IrrlichtCMake.dir/build.make CMakeFiles/IrrlichtCMake.dir/Src/Map.cpp.i
.PHONY : Src/Map.cpp.i

Src/Map.s: Src/Map.cpp.s

.PHONY : Src/Map.s

# target to generate assembly for a file
Src/Map.cpp.s:
	$(MAKE) -f CMakeFiles/IrrlichtCMake.dir/build.make CMakeFiles/IrrlichtCMake.dir/Src/Map.cpp.s
.PHONY : Src/Map.cpp.s

Src/Sphere.o: Src/Sphere.cpp.o

.PHONY : Src/Sphere.o

# target to build an object file
Src/Sphere.cpp.o:
	$(MAKE) -f CMakeFiles/IrrlichtCMake.dir/build.make CMakeFiles/IrrlichtCMake.dir/Src/Sphere.cpp.o
.PHONY : Src/Sphere.cpp.o

Src/Sphere.i: Src/Sphere.cpp.i

.PHONY : Src/Sphere.i

# target to preprocess a source file
Src/Sphere.cpp.i:
	$(MAKE) -f CMakeFiles/IrrlichtCMake.dir/build.make CMakeFiles/IrrlichtCMake.dir/Src/Sphere.cpp.i
.PHONY : Src/Sphere.cpp.i

Src/Sphere.s: Src/Sphere.cpp.s

.PHONY : Src/Sphere.s

# target to generate assembly for a file
Src/Sphere.cpp.s:
	$(MAKE) -f CMakeFiles/IrrlichtCMake.dir/build.make CMakeFiles/IrrlichtCMake.dir/Src/Sphere.cpp.s
.PHONY : Src/Sphere.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... IrrlichtCMake"
	@echo "... edit_cache"
	@echo "... Src/ActionManager.o"
	@echo "... Src/ActionManager.i"
	@echo "... Src/ActionManager.s"
	@echo "... Src/Clock.o"
	@echo "... Src/Clock.i"
	@echo "... Src/Clock.s"
	@echo "... Src/Cube.o"
	@echo "... Src/Cube.i"
	@echo "... Src/Cube.s"
	@echo "... Src/GraphicManager.o"
	@echo "... Src/GraphicManager.i"
	@echo "... Src/GraphicManager.s"
	@echo "... Src/Main.o"
	@echo "... Src/Main.i"
	@echo "... Src/Main.s"
	@echo "... Src/Map.o"
	@echo "... Src/Map.i"
	@echo "... Src/Map.s"
	@echo "... Src/Sphere.o"
	@echo "... Src/Sphere.i"
	@echo "... Src/Sphere.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

